#Modus properties
oAuth:
  host: "auth.appdataroom.com"
  path: "/oauth/token"

  
GET:
  host: "api3.appdataroom.com"
  path: "/folders"
  params:
    folderIdUri: "176307"
    depthQuery: "4"

error:
  clientId: "875c068dc4d742b19c64afdb960f46f7"
  clientSecret: "BA8C8357c7d74dB08f2F73e451269c0A"