#oAuth Cred details

oAuth:
  client_secret: "![OT3OlvE4NOVIZqZnBYzANZ/aIDqoqN2L]"
  password: "![FXkkl7UEXGey2fPHByv+Lg==]"
  grant_type: "![GCzcrRxspAoIHa9YJ23CcQ==]"
  username: "![LViuKOhE4afkatYIkMjpv9MPBDq481oX/ujcJS850p8=]"
  client_id: "![H49O9JwFy65rWO6ZBECOHnP0uRnClLzA]"
