#oAuth Cred details

oAuth:
  client_secret: "![OT3OlvE4NOVIZqZnBYzANZ/aIDqoqN2L]"
  password: "![GrDFf+HPz6EYUWV0pCraTw==]"
  grant_type: "![GCzcrRxspAoIHa9YJ23CcQ==]"
  username: "![UdZpWujVlMlwuZ2HLNPkGLPj9NFfzG5lndii305NhuRSm8Jk6j1i3Q==]"
  client_id: "![H49O9JwFy65rWO6ZBECOHnP0uRnClLzA]"
